export const stableDemoText = Object.freeze({
    brandSubtitle: "Cartographie musicale",
    intro: "Les territoires de la musique se révèlent au fil de tes écoutes.",
    explorer: "Explorer",
    history: "Chronologie",
    era: "Époque",
    present: "Présent de l’Atlas",
    pirateRadio: "Radio Pirate",
    radioHelp: "Sur les ondes, hors du temps de l’Atlas",
    close: "Fermer le panneau",
    presentIn: "Présent dans",
    territories: "territoires",
    insideBuilding: "Pistes à l’intérieur du bâtiment",
    country: "Pays",
    formed: "Fondé en",
    year: "Année",
    duration: "Durée",
    kinds: Object.freeze({
        genre: "Continent musical",
        artist: "District d’artiste",
        album: "Bâtiment d’album",
        track: "Piste",
        label: "Label",
        playlist: "Playlist",
        compilation: "Compilation",
    }),
    geography: Object.freeze({
        genre: "Un grand territoire musical de l’Atlas.",
        artist: "Un quartier musical inscrit dans son territoire.",
        album: "Un bâtiment musical habité par ses pistes.",
        track: "Une piste conservée à l’intérieur de son album.",
        label: "Une identité musicale du catalogue.",
        playlist: "Une identité musicale du catalogue.",
        compilation: "Une identité musicale du catalogue.",
    }),
});
