/** Current application copy, isolated so a future translation catalog can replace it. */
export const uiText = Object.freeze({
    canvasLabel: "EchoAtlas navigable music atlas",
    title: "EchoAtlas",
    subtitle: "Cartographie musicale",
    navigationLabel: "Navigation principale",
    explorer: "Explorer",
    navigationHelp: "Drag to explore · Scroll to zoom",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arrière",
    recenter: "Recentrer la carte",
    journey: "Votre voyage",
    places: "Lieux",
    relations: "Relations",
    visible: "Visibles",
    closeSelection: "Close selected place",
    closeSymbol: "×",
    selectionDetails: "Music details",
    entityKinds: Object.freeze({
        artist: "Artist",
        album: "Album",
        track: "Track",
        label: "Label",
        playlist: "Playlist",
        genre: "Genre",
        compilation: "Compilation",
    }),
    fields: Object.freeze({
        country: "Country",
        formed: "Active since",
        year: "Year",
        duration: "Duration",
        trackNumber: "Track",
    }),
});
