/** Current application copy, isolated so a future translation catalog can replace it. */
export const uiText = Object.freeze({
    canvasLabel: "EchoAtlas navigable music atlas",
    title: "EchoAtlas",
    subtitle: "Cartographie musicale",
    navigationLabel: "Navigation principale",
    explorer: "Explorer",
    navigationHelp: "Drag to explore · Scroll to zoom",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arrière",
    recenter: "Recentrer la carte",
    journey: "Votre voyage",
    places: "Lieux",
    relations: "Relations",
    visible: "Visibles",
    closeSelection: "Close selected place",
    closeBroadcast: "Close Radio Pirate",
    closeSymbol: "×",
    selectionDetails: "Music details",
    connections: "Connexions dans l’atlas",
    noConnections: "Aucune connexion directe",
    moreConnections: "autres connexions",
    pirateRadio: "Radio Pirate",
    pirateRadioLandmark: "Open Radio Pirate current broadcast",
    currentBroadcastKind: "Diffusion en cours",
    currentListening: "Écoutes du moment",
    broadcastPlaylist: "Sur les ondes",
    broadcastingNow: "En diffusion",
    entityKinds: Object.freeze({
        artist: "Artist",
        album: "Album",
        track: "Track",
        label: "Label",
        playlist: "Playlist",
        genre: "Genre",
        compilation: "Compilation",
    }),
    fields: Object.freeze({
        country: "Country",
        formed: "Active since",
        year: "Year",
        duration: "Duration",
        trackNumber: "Track",
    }),
});
